image: debian:latest

before_script: |
  bash ./Tools/InstallBuildEnvironment.sh

Tests:
  stage: build
  script: |
    source .env
    make -j$(nproc --all)
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
