image: debian:latest

before_script: |
  sudo apt update
  sudo apt install -y \
    make gcc mingw-w64 wine wine32 cc65 emscripten curl python3 python3-pil \
    libsdl1.2-dev libsdl-image1.2-dev libsdl-ttf2.0-dev libsdl-mixer1.2-dev \
    libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev \
  ;
  curl https://apt.devkitpro.org/install-devkitpro-pacman | sudo bash
  sudo dkp-pacman -Sy nds-dev

Tests:
  stage: Tests
  script: |
    cd ./LibMultiSpacc/Examples
    for Example in */
    do
      cd ${Example}
      for Build in \
        "Target=LinuxPC MultiSpacc_Target=SDL12"
        "Target=LinuxPC MultiSpacc_Target=SDL20"
        "Target=WindowsPC MultiSpacc_Target=SDL12"
        "Target=WindowsPC MultiSpacc_Target=SDL20"
        "Target=Windows9x"
        "Target=NDS"
        "Target=NES"
      ; do
        make clean
        make -j$(nproc --all) ${Build}
      done
      cd ..
    done
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
