image: debian:latest

before_script: |
  sh ./Tools/InstallBuildEnvironment.sh

Tests:
  stage: build
  script: |
    make -j($nproc --all)
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
